### ISSUE TITLE
Saving the Workouts

### ISSUE THREAD

**Issue by zazwazandi13** [ccgs-10asd-2019/major-project-o0-boon-two#5]
I have the workouts stored in a list temporarily but I think we need to attach it to the SQL database. But it does not save correctly.

**Comment by 1012543** [comment]
you can save variables through this thing 

define:
var MyVariable = App.Current.Properties["SaveName"];

give value:
App.Current.Properties["SaveName"] = "1";

to use the variable just call MyVariable
